name: Sync to Hugging Face Hub
on:
  push:
    branches: [VPC]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4 to fix the warning
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Set identity so git doesn't complain
          git config --global user.email "hisaalujuniornelson@gmail.com"
          git config --global user.name "Hisaalu"
          
          # Use force push to ensure your VPC branch becomes the new main on HF
          git push --force https://hisaalunelson:$HF_TOKEN@huggingface.co/spaces/hisaalunelson/ROGELE VPC:main